---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-wear-watch
  namespace: app-space
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /wear
        backend:
          serviceName: webapp-wear
          servicePort: 8080
      - path: /watch
        backend:
          serviceName: webapp-video
          servicePort: 8080
      - backend:
            serviceName: nginx
            servicePort: 80
        path: /
        pathType: ImplementationSpecific
      - backend:
          serviceName: apache-svc
          servicePort: 80
        path: /apache
        pathType: ImplementationSpecific